// module: videos
export const VIDEOS_REQUEST = 'VIDEOS_REQUEST';
export const VIDEOS_SUCCESS = 'VIDEOS_SUCCESS';
export const VIDEOS_FAILED = 'VIDEOS_FAILED';

export const VIDEO_BY_ID_REQUEST = 'VIDEO_BY_ID_REQUEST';
export const VIDEO_BY_ID_SUCCESS = 'VIDEO_BY_ID_SUCCESS';
export const VIDEO_BY_ID_FAILED = 'VIDEO_BY_ID_FAILED';

export const DELETE_VIDEO_REQUEST = 'DELETE_VIDEO_REQUEST';
export const DELETE_VIDEO_SUCCESS = 'DELETE_VIDEO_SUCCESS';
export const DELETE_VIDEO_FAILED = 'DELETE_VIDEO_FAILED';

export const UPLOAD_START = 'UPLOAD_START';
export const UPLOAD_PROGRESS = 'UPLOAD_PROGRESS';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAILED = 'UPLOAD_FAILED';

export const TAGS_SET = 'TAGS_SET';

export const ADD_TAG_REQUEST = 'ADD_TAG_REQUEST';
export const ADD_TAG_SUCCESS = 'ADD_TAG_SUCCESS';
export const ADD_TAG_FAILED = 'ADD_TAG_FAILED';

export const GEOLOCATION_SET = 'GEOLOCATION_SET';

export const PROCESSING_VIDEOS_REQUEST = 'PROCESSING_VIDEOS_REQUEST';
export const PROCESSING_VIDEOS_SUCCESS = 'PROCESSING_VIDEOS_SUCCESS';
export const PROCESSING_VIDEOS_FAILED = 'PROCESSING_VIDEOS_FAILED';

// module: feeds
export const FEEDS_FETCH_REQUEST = 'FEEDS_FETCH_REQUEST';
export const FEEDS_FETCH_SUCCESS = 'FEEDS_FETCH_SUCCESS';
export const FEEDS_FETCH_FAILED = 'FEEDS_FETCH_FAILED';

export const FEED_DELETE_REQUEST = 'FEED_DELETE_REQUEST';
export const FEED_DELETE_SUCCESS = 'FEED_DELETE_SUCCESS';
export const FEED_DELETE_FAILED = 'FEED_DELETE_FAILED';

export const FEED_RESTART_REQUEST = 'FEED_RESTART_REQUEST';
export const FEED_RESTART_SUCCESS = 'FEED_RESTART_SUCCESS';
export const FEED_RESTART_FAILED = 'FEED_RESTART_FAILED';

export const FEED_START_REQUEST = 'FEED_START_REQUEST';
export const FEED_START_SUCCESS = 'FEED_START_SUCCESS';
export const FEED_START_FAILED = 'FEED_START_FAILED';

// module: scandirectory
export const SCANDIR_INFOS_FETCH_REQUEST = 'SCANDIR_INFOS_FETCH_REQUEST';
export const SCANDIR_INFOS_FETCH_SUCCESS = 'SCANDIR_INFOS_FETCH_SUCCESS';
export const SCANDIR_INFOS_FETCH_FAILED = 'SCANDIR_INFOS_FETCH_FAILED';

export const SCANDIR_ENTRIES_FETCH_REQUEST = 'SCANDIR_ENTRIES_FETCH_REQUEST';
export const SCANDIR_ENTRIES_FETCH_SUCCESS = 'SCANDIR_ENTRIES_FETCH_SUCCESS';
export const SCANDIR_ENTRIES_FETCH_FAILED = 'SCANDIR_ENTRIES_FETCH_FAILED';

export const SCANDIR_ACTION_REQUEST = 'SCANDIR_ACTION_REQUEST';
export const SCANDIR_ACTION_SUCCESS = 'SCANDIR_ACTION_SUCCESS';
export const SCANDIR_ACTION_FAILED = 'SCANDIR_ACTION_FAILED';

export const SCANDIR_DELETE_REQUEST = 'SCANDIR_DELETE_REQUEST';
export const SCANDIR_DELETE_SUCCESS = 'SCANDIR_DELETE_SUCCESS';
export const SCANDIR_DELETE_FAILED = 'SCANDIR_DELETE_FAILED';
